Repository FRONTENDBOOTCAMP-13th/Final-14-z1zone1004, pull requests merged in 2025-07, with the labels that each got.

#11 Feat/list/ktw
  src/app/error.tsx
  src/app/list/[product]/[id]/page.tsx
  src/app/list/[product]/page.tsx
  src/assets/icons/doubleLeft.svg
  src/assets/icons/doubleRight.svg
  src/assets/icons/left.svg
  src/assets/icons/right.svg
  src/components/PageBottomNav.tsx
  src/components/SelectBar.tsx
Labels: enhancement, P1, frontend

#14 Feat/list-select-bar/ktw
  src/app/globals.css
  src/app/list/[product]/[id]/page.tsx
  src/app/list/[product]/page.tsx
  src/components/PageBottomNav.tsx
  src/components/SelectBar.tsx
Labels: frontend, UI/UX

#20 ✨ feat: implement notice creation feature #9
  src/app/notice/page.tsx
Labels: P2, in progress, frontend

#23 ✨ feat: 상품 목록 SelectBar ui 구현 #14
  src/app/globals.css
  src/app/list/[product]/page.tsx
  src/assets/icons/selector-arrow.svg
  src/components/PageBottomNav.tsx
  src/components/SelectBar.tsx
Labels: enhancement, UI/UX

#53 [feat] myPage 폴더 구조 설정 (#43)
  src/app/myPage/address/page.tsx
  src/app/myPage/layout.tsx
  src/app/myPage/like/page.tsx
  src/app/myPage/mypost/page.tsx
  src/app/myPage/page.tsx
  src/app/myPage/profile/page.tsx
  src/components/MyPage/MyPageSide.tsx
  src/components/MyPage/MyPageTop.tsx
Labels: enhancement, P1

#66 💄 ui: 상세 상품 페이지 UI 구현 #54
  src/app/list/[id]/page.tsx
  src/app/list/page.tsx
  src/assets/icons/heart-filled.svg
  src/components/MainCard/MainCardInfo.tsx
  src/components/SelectBar.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardContext.tsx
  src/components/list-ItemCard/ItemCardImage.tsx
  src/components/list-ItemCard/ItemCardInfo.tsx
  src/components/list-ItemCard/ItemNumInput.tsx
  src/components/list-ItemCard/ItemNumSpinner.tsx
Labels: in progress, frontend, UI/UX

#70 ✨ feat: 마이페이지 UI 구현 #21
  src/app/myPage/address/page.tsx
  src/app/myPage/mypost/page.tsx
  src/app/myPage/page.tsx
  src/components/MyPage/MyPageSide.tsx
  src/components/MyPage/MyPageTop.tsx
Labels: bug, enhancement, frontend

#74 💄 ui: 상품 목록 페이지 ui 업데이트 #66
  api/bruno/potengame/02_상품/상품 목록조회.bru
  api/bruno/potengame/02_상품/상품 상세조회.bru
  src/app/list/[id]/page.tsx
  src/app/list/page.tsx
  src/components/List-ItemDetail/ItemDetail.tsx
  src/components/List-ItemDetail/ItemDetailHeader.tsx
  src/components/List-ItemDetail/ItemDetailImage.tsx
  src/components/List-ItemDetail/ItemDetailInfo.tsx
  src/components/List-ItemDetail/ItemDetailNotice.tsx
  src/components/List-ItemDetail/ItemDetailReview.tsx
  src/components/Pagination.tsx
  src/components/SelectBar.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardImage.tsx
  src/components/list-ItemCard/ItemCardInfo.tsx
  src/components/list-ItemCard/ItemNumInput.tsx
  src/components/list-ItemCard/ItemNumSpinner.tsx
Labels: frontend, UI/UX

#78 ✨ feat: 상품 목록 페이지 기능 구현 #76
  api/bruno/potengame/02_상품/상품 목록조회.bru
  src/app/list/page.tsx
  src/components/SelectBar.tsx
  src/components/Tags.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardContext.tsx
  src/components/list-ItemCard/ItemCardImage.tsx
  src/components/list-ItemCard/ItemCardInfo.tsx
  src/data/functions/listProducts.ts
  src/types/sort.ts
  src/zustand/listStore.ts
Labels: enhancement, P1, frontend

#85 ✨ feat: 상품 목록 페이지 기능 구현 #76
  api/bruno/potengame/02_상품/상품 목록조회.bru
  src/app/list/page.tsx
  src/components/Pagination.tsx
  src/zustand/listStore.ts
Labels: enhancement, P1, frontend

#88 [기능 요청] 마이페이지 기능 구현 1st #81
  src/app/myPage/page.tsx
  src/components/MyPage/MyPageOrder.tsx
  src/components/MyPage/MyPageTop.tsx
  src/data/functions/getMyPage.ts
  src/data/functions/getUserInfo.ts
  src/types/Order.ts
  src/types/myorder.ts
Labels: enhancement, P1, in progress, API

#91 💄style : 마이페이지 ui 수정
  src/app/api/myorder/route.ts
  src/components/MyPage/MyPageOrder.tsx
  src/components/MyPage/MyPageTop.tsx
  src/types/user.ts
Labels: enhancement, P1, in progress, API
