Repository FRONTENDBOOTCAMP-13th/Final-14-z1zone1004, pull requests merged in 2025-08, with the labels that each got.

#101 [ 기능 추가 ] 마이페이지 최근 주문 현황과 주소록 기능 추가
  src/app/myPage/page.tsx
  src/components/MyPage/Address/AddressCards.tsx
  src/components/MyPage/Address/AddressList.tsx
  src/components/MyPage/EmptyState.tsx
  src/components/MyPage/MyPageRecent.tsx
  src/types/MyAddress.ts
  src/types/RecentOrder.ts
Labels: enhancement, P1, in progress, hard

#110 ✨ feat: 상품 목록 페이지 메인 페이지와 기능 연결 #76
  src/app/list/[category]/[id]/page.tsx
  src/app/list/[category]/page.tsx
  src/app/list/[id]/page.tsx
  src/app/list/page.tsx
  src/components/AllProductList.tsx
  src/components/CategoryProductList.tsx
  src/components/Header/Nav.tsx
  src/components/Header/TopNavElem.tsx
  src/components/List-ItemDetail/ItemDetail.tsx
  src/components/List-ItemDetail/ItemDetailImage.tsx
  src/components/List-ItemDetail/ItemDetailReview.tsx
  src/components/SelectBar.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardImage.tsx
  src/components/list-ItemCard/ItemCardInfo.tsx
  src/utils/filterUtils.ts
  src/zustand/errorStore.ts
Labels: P1, refactor, frontend

#115 ✨ feat: 상품 목록 페이지 기능 구현 #76
  src/components/AllProductList.tsx
  src/components/CategoryProductList.tsx
  src/components/Header/Nav.tsx
  src/components/List-ItemDetail/ItemDetailImage.tsx
  src/components/MainGameLink/SliderLink.tsx
  src/components/SelectBar.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardImage.tsx
  src/data/functions/listProducts.ts
  src/types/products.ts
  src/zustand/listStore.ts
Labels: enhancement, P1, frontend

#121 ✨ [Feat] : 마이페이지 반응형과 삭제 기능 수정 완료
  src/app/myPage/page.tsx
  src/components/MyPage/Address/AddressCards.tsx
  src/components/MyPage/Address/AddressList.tsx
  src/components/MyPage/Address/AddressModal.tsx
  src/components/MyPage/MyPageOrder.tsx
  src/components/MyPage/MyPageRecent.tsx
  src/components/MyPage/MyPageTop.tsx
  src/types/MyAddressForm.ts
  src/types/user.ts
  src/zustand/userAddress.ts
Labels: enhancement, good first issue, P1, refactor, UI/UX

#125 ✨ feat: 상품 상세 페이지 기능 추가 구현 #116
  api/bruno/potengame/02_상품/상품 목록조회.bru
  src/app/layout.tsx
  src/app/page.tsx
  src/components/list-ItemCard/ItemCard.tsx
  src/components/list-ItemCard/ItemCardInfo.tsx
  src/components/list-ItemCard/ItemLikeBtn.tsx
  src/data/functions/listProducts.ts
Labels: enhancement, frontend

#140 🐛 bug: 상품 목록 페이지 /list/[category] SelectBar 버그 수정 #116
  src/components/CategoryProductList.tsx
  src/data/functions/listProducts.ts
Labels: bug

#153 ✨feat : 마이페이지 배송 신규 버튼 리팩토링 완료/ 리드미 수정 완료
  README.md
  src/components/MyPage/Address/AddressCards.tsx
  src/components/MyPage/Address/AddressList.tsx
Labels: documentation, enhancement, P2

#157 📝 docs : 리드미 내용 추가 수정
  README.md
Labels: documentation
